version: '3.8'
services:
  web:
    image: petrichao/k12:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/k12_spb_ru.crt:/etc/nginx/ssl/k12_spb_ru.crt
      - ./nginx/private.key:/etc/nginx/ssl/private.key
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
