# Generated by Django 3.2.18 on 2023-03-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230302_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admission_lists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='users.admission', verbose_name='Список на допуск'),
        ),
    ]
