# Generated by Django 3.2.18 on 2023-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_company_admission_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admission_lists',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
