from django.urls import path
from info import views

app_name = "info"

urlpatterns = [
    path("",
         views.MainPage.as_view(),
         name="index"),
    path("server_placement/",
         views.ServerPlacement.as_view(),
         name="ServerPlacement",
         ),
    path("rent_of_server_racks/",
         views.RentOfServerRacks.as_view(),
         name="RentOfServerRacks",
         ),
    path("rent_of_space_for_equipment/",
         views.RentOfSpaceForEquipment.as_view(),
         name="RentOfSpaceForEquipment",
         ),
    path("crossing/",
         views.Crossing.as_view(),
         name="Crossing",
         ),
    path("service/",
         views.Service.as_view(),
         name="Service",
         ),
    path("internet_access/",
         views.InternetAccess.as_view(),
         name="InternetAccess",
         ),
    path("about/",
         views.About.as_view(),
         name="About",
         ),
    path("contact/",
         views.Contact.as_view(),
         name="Contact",
         ),
    path("order_call/",
         views.order_call,
         name="OrderCall",
         ),
    path("thanks/",
         views.Thanks.as_view(),
         name="Thanks",
         ),
]